### ISSUE TITLE
Display board game covers as boxes

### ISSUE THREAD

**Issue by JanWennrich** [JanWennrich/boardgames#8]
The plain 2D board game cover images could be displayed as a 3D box:

![image](https://github.com/user-attachments/assets/e3a1c011-0106-46a1-a3d3-fc57e69fce22)  
vs.  
![image](https://github.com/user-attachments/assets/d7f03a41-a013-4a57-ae2f-05e2cce065fc)

```html
<div class="boardgame">
  <div class="box-border box-border-top"></div>
  <div class="box">
    <img src="https://via.assets.so/game.png?&w=150&h=150&fit=fill"/>
  </div>
  <div class="box-border box-border-right">
</div>
```

```css
.boardgame {
  position: relative;
  top: 100px;
}

.box-border-top {
  width: 150px;
  height: 20px;
  background-color: black;
  transform: skew(-45deg);
  position: absolute;
  top: -20px;
  left: 10px;
}

.box-border-right {
  height: 150px;
  width: 20px;
  background-color: black;
  transform: skew(0, -45deg);
  position: absolute;
  top: -10px;
  left: 150px;
}
```
